version: '3'

services:
  app:
    working_dir: /var/www
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    entrypoint: dockerize -template ./.docker/app/.env:.env -template ./.docker/app/.env:.env.testing  -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    tty: true
    environment:
      - DB_HOST=db
      - DB_DATABASE=finxi
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - NGINX_HOST=app
      - NGINX_PORT=9000
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    build: .docker/nginx
    container_name: nginx_laravel
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db_laravel
    restart: always
    tty: true
    ports:
      - "3308:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=finxi
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
